# Cassandra Cluster
apiVersion: cassandra.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cassandra
  namespace: rook-cassandra
spec:
  version: 3.11.1
  mode: cassandra
  annotations:
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        members: 2
        storage:
          volumeClaimTemplates:
                - metadata:
                    name: rook-cassandra-data
                  spec:
                    storageClassName: nfs-client
                    resources:
                      requests:
                        storage: 5Gi
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi

